apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: otm8tzb3l-dotnet-basic
  janus-idp.io/tekton: otm8tzb3l-dotnet-basic
  backstage.io/kubernetes-id: otm8tzb3l-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: otm8tzb3l-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
